# Finne høyfrekvente stasjoner

Vi ønsker å finne stasjoner/holdeplasser som tilfredsstiller ulike definisjoner av høyfrekvent.

In [57]:
import polars as pl
import polars.selectors as cs

### Data fra Entur

Tre tabeller er lastet ned fra Enturs datakatalog. SQL-koden er gjengitt under. 


Vi ser kun på en dato, nemlig 2026-01-15.

Koden under gir en rutetabell for Norge torsdag 15. januar 2026. 

```sql
SELECT 
    agency_name,
    route_id, route_short_name, route_long_name, route_type, 
    trip_id, trip_headsign, direction_id, shape_dist_traveled,
    stop_id, stop_sequence, 
    DATETIME(departure_time, "Europe/Oslo") AS departure_time_oslo,
    DATETIME(arrival_time, "Europe/Oslo") AS arrival_time_oslo
FROM `ent-data-sharing-ext-prd.timetable_gtfs.gtfs_last_recorded_ent_v1`
WHERE operating_date = '2026-01-15'
```

In [58]:
# resultatet fra koden over er lagret bq-results-20260206-080556-1770365220476.csv
alle_avganger = (
    pl.scan_csv("bq-results-20260206-080556-1770365220476.csv", schema_overrides={"route_short_name":pl.Utf8})
    .with_columns(
        pl.col("departure_time_oslo").str.to_datetime(format="%Y-%m-%d %H:%M:%S", time_zone="Europe/Oslo"),
        pl.col("arrival_time_oslo").str.to_datetime(format="%Y-%m-%d %H:%M:%S", time_zone="Europe/Oslo")
    )
    .rename({"departure_time_oslo":"departure_time", "arrival_time_oslo":"arrival_time"})
)

print(f"Det er {alle_avganger.select(pl.col("stop_id").len()).collect().item():,} antall rader i rutetabellen.\nSer sånn ut:")
alle_avganger.head(3).collect()

Det er 1,838,090 antall rader i rutetabellen.
Ser sånn ut:

shape: (3, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ agency_na ┆ route_id  ┆ route_sho ┆ route_lon ┆ … ┆ stop_id   ┆ stop_sequ ┆ departure ┆ arrival_ │
│ me        ┆ ---       ┆ rt_name   ┆ g_name    ┆   ┆ ---       ┆ ence      ┆ _time     ┆ time     │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆ str       ┆ str       ┆   ┆           ┆ i64       ┆ datetime[ ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs, Europ ┆ [μs, Eur │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ e/Oslo]   ┆ ope/Oslo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Østfold   ┆ OST:Line: ┆ 477       ┆ Mysen     ┆ … ┆ NSR:Quay: ┆ 10        ┆ 2026-01-1 ┆ 2026-01- │
│ kollektiv ┆ 1_477     ┆           ┆ vgs.      ┆   ┆ 100103    ┆           ┆ 5         ┆ 15       │
│ trafikk   ┆           ┆           ┆           ┆   ┆           ┆           ┆ 14:14:00  ┆ 14:14:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CET       ┆ CET      │
│ Østfold   ┆ OST:Line: ┆ 206       ┆ Krossern- ┆ … ┆ NSR:Quay: ┆ 3         ┆ 2026-01-1 ┆ 2026-01- │
│ kollektiv ┆ 1_206     ┆           ┆ Orkerød   ┆   ┆ 100110    ┆           ┆ 5         ┆ 15       │
│ trafikk   ┆           ┆           ┆           ┆   ┆           ┆           ┆ 18:17:00  ┆ 18:17:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CET       ┆ CET      │
│ Østfold   ┆ OST:Line: ┆ 206       ┆ Krossern- ┆ … ┆ NSR:Quay: ┆ 3         ┆ 2026-01-1 ┆ 2026-01- │
│ kollektiv ┆ 1_206     ┆           ┆ Orkerød   ┆   ┆ 100110    ┆           ┆ 5         ┆ 15       │
│ trafikk   ┆           ┆           ┆           ┆   ┆           ┆           ┆ 17:47:00  ┆ 17:47:00 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ CET       ┆ CET      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

```sql
SELECT 
    id, version, publicCode, transportMode, name, shortName, 
    description, location_longitude, location_latitude, 
    parentRef.ref AS parentRef_ref, parentRef.version AS parentRef_version 
FROM 
    `ent-data-sharing-ext-prd.national_stop_registry.stop_places_all_versions
````

In [59]:
stoppesteder = (
    pl.scan_csv("bq-results-20260206-082744-1770366470007.csv")
    .filter(pl.col("version")==pl.col("version").max().over("id"))
) 
print(stoppesteder.select(pl.col("id").len().alias("nrow"),pl.col("id").unique().len().alias("n_unique_id")).collect())
stoppesteder.head(3).collect()

shape: (1, 2)
┌───────┬─────────────┐
│ nrow  ┆ n_unique_id │
│ ---   ┆ ---         │
│ u32   ┆ u32         │
╞═══════╪═════════════╡
│ 64438 ┆ 64438       │
└───────┴─────────────┘

shape: (3, 11)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ version ┆ publicCod ┆ transport ┆ … ┆ location_ ┆ location_ ┆ parentRef ┆ parentRef │
│ ---        ┆ ---     ┆ e         ┆ Mode      ┆   ┆ longitude ┆ latitude  ┆ _ref      ┆ _version  │
│ str        ┆ i64     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆ str       ┆ str       ┆   ┆ f64       ┆ f64       ┆ str       ┆ i64       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ NSR:StopPl ┆ 27      ┆ null      ┆ BUS       ┆ … ┆ 10.760974 ┆ 59.918394 ┆ NSR:StopP ┆ 20        │
│ ace:6459   ┆         ┆           ┆           ┆   ┆           ┆           ┆ lace:5825 ┆           │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆ 3         ┆           │
│ NSR:StopPl ┆ 7       ┆ null      ┆ BUS       ┆ … ┆ 10.887819 ┆ 59.953365 ┆ NSR:StopP ┆ 6         │
│ ace:5899   ┆         ┆           ┆           ┆   ┆           ┆           ┆ lace:5964 ┆           │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆ 5         ┆           │
│ NSR:StopPl ┆ 4       ┆ null      ┆ BUS       ┆ … ┆ 11.25553  ┆ 60.563193 ┆ null      ┆ null      │
│ ace:7215   ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

``` sql
SELECT 
    id, version, publicCode, name, description, 
    location_longitude, location_latitude, stopPlaceRef, 
    stopPlaceVersion 
FROM 
    `ent-data-sharing-ext-prd.national_stop_registry.quays_all_versions`
```

In [60]:
quays = (
    pl.scan_csv("bq-results-20260206-082949-1770366598757.csv")
    .filter(pl.col("version")==pl.col("version").max().over("id"))
)
quays.head(3).collect()

shape: (3, 9)
┌────────────┬─────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id         ┆ version ┆ publicCode ┆ name ┆ … ┆ location_l ┆ location_l ┆ stopPlaceR ┆ stopPlaceV │
│ ---        ┆ ---     ┆ ---        ┆ ---  ┆   ┆ ongitude   ┆ atitude    ┆ ef         ┆ ersion     │
│ str        ┆ i64     ┆ str        ┆ str  ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│            ┆         ┆            ┆      ┆   ┆ f64        ┆ f64        ┆ str        ┆ i64        │
╞════════════╪═════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ NSR:Quay:1 ┆ 36      ┆            ┆ null ┆ … ┆ 10.75525   ┆ 59.909548  ┆ NSR:StopPl ┆ 36         │
│            ┆         ┆            ┆      ┆   ┆            ┆            ┆ ace:2      ┆            │
│ NSR:Quay:1 ┆ 17      ┆ 4          ┆ null ┆ … ┆ 7.987168   ┆ 58.14577   ┆ NSR:StopPl ┆ 17         │
│ 000        ┆         ┆            ┆      ┆   ┆            ┆            ┆ ace:609    ┆            │
│ NSR:Quay:1 ┆ 15      ┆ 1          ┆ null ┆ … ┆ 15.211521  ┆ 59.278877  ┆ NSR:StopPl ┆ 16         │
│ 00005      ┆         ┆            ┆      ┆   ┆            ┆            ┆ ace:570    ┆            │
└────────────┴─────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴────────────┘

In [61]:
alle_avganger = (
    alle_avganger
    .join(
        quays.select("id", "stopPlaceRef"), 
        left_on="stop_id", right_on="id",
        how="left"
    )
    .join(
        stoppesteder.rename({"parentRef_ref":"parent_station"}).select("id", "name", "parent_station"),
        left_on="stopPlaceRef", right_on="id"
    )
)

Vi ønsker å behandle bussveien i Nord-Jæren som ikke-buss. Det har vært vanskelig å oppdrive fine tabeller som oppgir hvilke stasjoner som er del av Bussveien. Jeg tror rutene 1,2,3 og 43

In [62]:
# stopplaces_not_included = [
#     "NSR:StopPlace:27927", "NSR:StopPlace:27035", "NSR:StopPlace:27047",
#     "NSR:StopPlace:28523", "NSR:StopPlace:27039", "NSR:StopPlace:25931",
#     "NSR:StopPlace:28127", "NSR:StopPlace:26716", "NSR:StopPlace:26719",
#     "NSR:StopPlace:27195", "NSR:StopPlace:27813", "NSR:StopPlace:27181",
#     "NSR:StopPlace:27383", "NSR:StopPlace:26657", "NSR:StopPlace:27973",
#     "NSR:StopPlace:27977", "NSR:StopPlace:28144", "NSR:StopPlace:26773",
#     "NSR:StopPlace:26133", "NSR:StopPlace:26137", "NSR:StopPlace:27440",
#     "NSR:StopPlace:28813", "NSR:StopPlace:28312", "NSR:StopPlace:27788",
#     "NSR:StopPlace:28803", "NSR:StopPlace:28804", "NSR:StopPlace:27480",
#     "NSR:StopPlace:28062", "NSR:StopPlace:28065", "NSR:StopPlace:26525"
#     ]


# busslinjen_stopplaces = (
#     alle_avganger
#     .filter(
#         pl.col("agency_name")=="Kolumbus",
#         pl.col("route_short_name").is_in(["1", "2", "3", "42"])
#     )
#     .select("stop_id", "stopPlaceRef")
#     .unique()
#     .join(stoppesteder.select("id", cs.starts_with("location")), left_on="stopPlaceRef", right_on="id", how="left")
#     .filter(
#         ((pl.col("location_latitude")>58.969188398795595) & (pl.col("location_longitude")>5.702509477827003)).not_()
#     )
#     .filter(pl.col("stopPlaceRef").is_in(stopplaces_not_included).not_())
#     # .drop(cs.starts_with("location"))
#     .collect()
# )

# print(busslinjen_stopplaces.head())

# from lonboard import viz
# import geopandas as gpd
# viz(gpd.GeoDataFrame(busslinjen_stopplaces, geometry=gpd.points_from_xy(busslinjen_stopplaces["location_longitude"], busslinjen_stopplaces["location_latitude"]), crs=4326))

In [63]:
stopplaces_included_in_bussveien = [
    "NSR:StopPlace:60623", "NSR:StopPlace:63166", "NSR:StopPlace:27023",
    "NSR:StopPlace:28541", "NSR:StopPlace:25924", "NSR:StopPlace:26965",
    "NSR:StopPlace:26957", "NSR:StopPlace:25844", "NSR:StopPlace:28521",
    "NSR:StopPlace:26171", "NSR:StopPlace:27787", "NSR:StopPlace:28073",
    "NSR:StopPlace:26856", "NSR:StopPlace:27398", "NSR:StopPlace:27951",
    "NSR:StopPlace:28368", "NSR:StopPlace:27222", "NSR:StopPlace:28371",
    "NSR:StopPlace:28515", "NSR:StopPlace:28567", "NSR:StopPlace:28569", 
    "NSR:StopPlace:28564", "NSR:StopPlace:63153", "NSR:StopPlace:63155",
    "NSR:StopPlace:63156", "NSR:StopPlace:63157", "NSR:StopPlace:27338",
    "NSR:StopPlace:27461", "NSR:StopPlace:27981", "NSR:StopPlace:26208",
    "NSR:StopPlace:27805", "NSR:StopPlace:26441", "NSR:StopPlace:26444",
    "NSR:StopPlace:28107", "NSR:StopPlace:26913", "NSR:StopPlace:26353",
    "NSR:StopPlace:27107", "NSR:StopPlace:26210", "NSR:StopPlace:27711",
    "NSR:StopPlace:27742"
    ]

In [64]:
alle_avganger = (
    alle_avganger
    .with_columns(
        pl.when(pl.col("stopPlaceRef").is_in(stopplaces_included_in_bussveien)).then(pl.lit("Bussveien")).otherwise("route_type").alias("route_type")
    )
)

In [65]:
alle_avganger.head(2).collect()

shape: (2, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ agency_na ┆ route_id  ┆ route_sho ┆ route_lon ┆ … ┆ arrival_t ┆ stopPlace ┆ name      ┆ parent_s │
│ me        ┆ ---       ┆ rt_name   ┆ g_name    ┆   ┆ ime       ┆ Ref       ┆ ---       ┆ tation   │
│ ---       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│ str       ┆           ┆ str       ┆ str       ┆   ┆ datetime[ ┆ str       ┆           ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ μs, Europ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e/Oslo]   ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Østfold   ┆ OST:Line: ┆ 477       ┆ Mysen     ┆ … ┆ 2026-01-1 ┆ NSR:StopP ┆ Åsland    ┆ null     │
│ kollektiv ┆ 1_477     ┆           ┆ vgs.      ┆   ┆ 5         ┆ lace:6003 ┆           ┆          │
│ trafikk   ┆           ┆           ┆           ┆   ┆ 14:14:00  ┆ 7         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ CET       ┆           ┆           ┆          │
│ Østfold   ┆ OST:Line: ┆ 206       ┆ Krossern- ┆ … ┆ 2026-01-1 ┆ NSR:StopP ┆ Gimleveie ┆ null     │
│ kollektiv ┆ 1_206     ┆           ┆ Orkerød   ┆   ┆ 5         ┆ lace:3060 ┆ n fv. 312 ┆          │
│ trafikk   ┆           ┆           ┆           ┆   ┆ 18:17:00  ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ CET       ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [66]:
alle_avganger.group_by("route_type").len().collect()

shape: (6, 2)
┌────────────┬─────────┐
│ route_type ┆ len     │
│ ---        ┆ ---     │
│ str        ┆ u32     │
╞════════════╪═════════╡
│ Bus        ┆ 1706108 │
│ Subway     ┆ 31774   │
│ Train      ┆ 22682   │
│ Tram       ┆ 44562   │
│ Bussveien  ┆ 17717   │
│ Ferry      ┆ 15247   │
└────────────┴─────────┘

### Se på ulike definisjoner

#### Høyfrekvente ruter

Bussrute hvert 10. minutt. Andre ruter hvert 15.

In [67]:
pl.read_parquet("stasjoner_med_frekvens_10_15_7_20.parquet").shape

(824, 6)

##### 7-20

In [68]:
start_time = pl.datetime(2026, 1, 15, 7, time_zone="Europe/Oslo")
end_time = pl.datetime(2026, 1, 15, 20, time_zone="Europe/Oslo")

timedelta_bus = pl.duration(minutes=10)
timedelta_not_bus = pl.duration(minutes=15)

frekvente_stoppesteder_7_20 = (
    alle_avganger
    .filter(pl.col("route_type")!="Ferry")
    .filter(pl.col("stop_sequence")!=pl.col("stop_sequence").max().over("trip_id"))
    .sort("departure_time")
    .with_columns(
        waiting_time = pl.col("departure_time").shift(-1).over("stop_id") - pl.col("departure_time")
    )
    .group_by(
        "stop_id", "parent_station", "stopPlaceRef", "route_type", "name"
    )
    .agg(
        max_waiting_time_bus = pl.col("waiting_time").filter(
                pl.col("departure_time")
                .is_between(
                    start_time,
                    end_time-timedelta_bus
                )
        ).max(),
        max_waiting_time_not_bus = pl.col("waiting_time").filter(
                pl.col("departure_time")
                .is_between(
                    start_time,
                    end_time-timedelta_not_bus
                )
        ).max(),
        first_departure = pl.col("departure_time").filter(pl.col("departure_time")>=start_time).min(),
        last_departure = pl.col("departure_time").filter(pl.col("departure_time")<=end_time).max()
    )
    .with_columns(
        pl.when(pl.col("route_type")=="Bus").then("max_waiting_time_bus").otherwise("max_waiting_time_not_bus").alias("max_waiting_time")
    )
    .drop(cs.contains("bus"))
    .filter(
        (
            (pl.col("route_type")=="Bus") & 
            (pl.col("max_waiting_time")<=timedelta_bus) & 
            (pl.col("first_departure")<=start_time + timedelta_bus) & 
            (pl.col("last_departure")>=end_time - timedelta_bus)
        ) |
        (
            (pl.col("route_type")!="Bus") & 
            (pl.col("max_waiting_time")<=timedelta_not_bus) & 
            (pl.col("first_departure")<=start_time + timedelta_not_bus) & 
            (pl.col("last_departure")>=end_time - timedelta_not_bus)
        )
    )
    .group_by("stopPlaceRef", "route_type", "name")
    .agg(pl.struct("stop_id", "first_departure", "last_departure", "max_waiting_time"))
    .join(stoppesteder.select("id", cs.contains("location")), left_on="stopPlaceRef", right_on="id", how="left")
    .collect()
)

frekvente_stoppesteder_7_20

shape: (848, 6)
┌─────────────────┬────────────┬────────────────┬────────────────┬────────────────┬────────────────┐
│ stopPlaceRef    ┆ route_type ┆ name           ┆ stop_id        ┆ location_longi ┆ location_latit │
│ ---             ┆ ---        ┆ ---            ┆ ---            ┆ tude           ┆ ude            │
│ str             ┆ str        ┆ str            ┆ list[struct[4] ┆ ---            ┆ ---            │
│                 ┆            ┆                ┆ ]              ┆ f64            ┆ f64            │
╞═════════════════╪════════════╪════════════════╪════════════════╪════════════════╪════════════════╡
│ NSR:StopPlace:6 ┆ Bus        ┆ Historisk      ┆ [{"NSR:Quay:10 ┆ 10.735021      ┆ 59.916915      │
│ 3281            ┆            ┆ museum         ┆ 9248",2026-01- ┆                ┆                │
│                 ┆            ┆                ┆ 15…            ┆                ┆                │
│ NSR:StopPlace:5 ┆ Subway     ┆ Bogerud        ┆ [{"NSR:Quay:10 ┆ 10.842064      ┆ 59.87606       │
│ 874             ┆            ┆                ┆ 769",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:2 ┆ Bussveien  ┆ Prestaskjersve ┆ [{"NSR:Quay:48 ┆ 5.603694       ┆ 58.954895      │
│ 8107            ┆            ┆ ien            ┆ 355",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:3 ┆ Bus        ┆ Morvikbotn     ┆ [{"NSR:Quay:55 ┆ 5.281779       ┆ 60.466963      │
│ 2426            ┆            ┆                ┆ 952",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:2 ┆ Bus        ┆ Brageveien     ┆ [{"NSR:Quay:48 ┆ 5.710388       ┆ 58.975505      │
│ 7506            ┆            ┆                ┆ 640",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ …               ┆ …          ┆ …              ┆ …              ┆ …              ┆ …              │
│ NSR:StopPlace:6 ┆ Bus        ┆ Kjelsås        ┆ [{"NSR:Quay:11 ┆ 10.782258      ┆ 59.965662      │
│ 121             ┆            ┆ stasjon        ┆ 238",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:3 ┆ Subway     ┆ Gjønnes        ┆ [{"NSR:Quay:69 ┆ 10.580089      ┆ 59.915056      │
│ 861             ┆            ┆                ┆ 29",2026-01-15 ┆                ┆                │
│                 ┆            ┆                ┆ 0…             ┆                ┆                │
│ NSR:StopPlace:2 ┆ Train      ┆ Oslo lufthavn  ┆ [{"NSR:Quay:45 ┆ 11.096735      ┆ 60.192981      │
│ 69              ┆            ┆ stasjon        ┆ 3",2026-01-15  ┆                ┆                │
│                 ┆            ┆                ┆ 07…            ┆                ┆                │
│ NSR:StopPlace:3 ┆ Bus        ┆ Henrik Jægers  ┆ [{"NSR:Quay:53 ┆ 5.36824        ┆ 60.350981      │
│ 1326            ┆            ┆ vei            ┆ 949",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:6 ┆ Bus        ┆ Torsbekken     ┆ [{"NSR:Quay:10 ┆ 11.098359      ┆ 59.284051      │
│ 1178            ┆            ┆                ┆ 4698",2026-01- ┆                ┆                │
│                 ┆            ┆                ┆ 15…            ┆                ┆                │
└─────────────────┴────────────┴────────────────┴────────────────┴────────────────┴────────────────┘

### 7-18

In [69]:
start_time = pl.datetime(2026, 1, 15, 7, time_zone="Europe/Oslo")
end_time = pl.datetime(2026, 1, 15, 18, time_zone="Europe/Oslo")
timedelta_bus = pl.duration(minutes=10)
timedelta_not_bus = pl.duration(minutes=15)

frekvente_stoppesteder_7_18 = (
    alle_avganger
    .filter(pl.col("route_type")!="Ferry")
    .filter(pl.col("stop_sequence")!=pl.col("stop_sequence").max().over("trip_id"))
    .sort("departure_time")
    .with_columns(
        waiting_time = pl.col("departure_time").shift(-1).over("stop_id") - pl.col("departure_time")
    )
    .group_by(
        "stop_id", "parent_station", "stopPlaceRef", "route_type", "name"
    )
    .agg(
        max_waiting_time_bus = pl.col("waiting_time").filter(
                pl.col("departure_time")
                .is_between(
                    start_time,
                    end_time-timedelta_bus
                )
        ).max(),
        max_waiting_time_not_bus = pl.col("waiting_time").filter(
                pl.col("departure_time")
                .is_between(
                    start_time,
                    end_time-timedelta_not_bus
                )
        ).max(),
        first_departure = pl.col("departure_time").filter(pl.col("departure_time")>=start_time).min(),
        last_departure = pl.col("departure_time").filter(pl.col("departure_time")<=end_time).max()
    )
    .with_columns(
        pl.when(pl.col("route_type")=="Bus").then("max_waiting_time_bus").otherwise("max_waiting_time_not_bus").alias("max_waiting_time")
    )
    .drop(cs.contains("bus"))
    .filter(
        (
            (pl.col("route_type")=="Bus") & 
            (pl.col("max_waiting_time")<=timedelta_bus) & 
            (pl.col("first_departure")<=start_time + timedelta_bus) & 
            (pl.col("last_departure")>=end_time - timedelta_bus)
        ) |
        (
            (pl.col("route_type")!="Bus") & 
            (pl.col("max_waiting_time")<=timedelta_not_bus) & 
            (pl.col("first_departure")<=start_time + timedelta_not_bus) & 
            (pl.col("last_departure")>=end_time - timedelta_not_bus)
        )
    )
    .group_by("stopPlaceRef", "route_type", "name")
    .agg(pl.struct("stop_id", "first_departure", "last_departure", "max_waiting_time"))
    .join(stoppesteder.select("id", cs.contains("location")), left_on="stopPlaceRef", right_on="id", how="left")
    .collect()
)

frekvente_stoppesteder_7_18

shape: (1_169, 6)
┌─────────────────┬────────────┬────────────────┬────────────────┬────────────────┬────────────────┐
│ stopPlaceRef    ┆ route_type ┆ name           ┆ stop_id        ┆ location_longi ┆ location_latit │
│ ---             ┆ ---        ┆ ---            ┆ ---            ┆ tude           ┆ ude            │
│ str             ┆ str        ┆ str            ┆ list[struct[4] ┆ ---            ┆ ---            │
│                 ┆            ┆                ┆ ]              ┆ f64            ┆ f64            │
╞═════════════════╪════════════╪════════════════╪════════════════╪════════════════╪════════════════╡
│ NSR:StopPlace:3 ┆ Bus        ┆ Ludebryggen    ┆ [{"NSR:Quay:53 ┆ 5.32331        ┆ 60.411026      │
│ 0933            ┆            ┆                ┆ 255",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:3 ┆ Bus        ┆ Breimyra       ┆ [{"NSR:Quay:53 ┆ 5.367506       ┆ 60.461361      │
│ 1234            ┆            ┆                ┆ 794",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:2 ┆ Bussveien  ┆ Seljeveien     ┆ [{"NSR:Quay:45 ┆ 5.728341       ┆ 58.874271      │
│ 6171            ┆            ┆                ┆ 343",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:6 ┆ Bus        ┆ Teisenkrysset  ┆ [{"NSR:Quay:11 ┆ 10.811134      ┆ 59.917376      │
│ 101             ┆            ┆                ┆ 205",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:5 ┆ Subway     ┆ Ryen           ┆ [{"NSR:Quay:10 ┆ 10.80488       ┆ 59.895691      │
│ 900             ┆            ┆                ┆ 819",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ …               ┆ …          ┆ …              ┆ …              ┆ …              ┆ …              │
│ NSR:StopPlace:5 ┆ Bus        ┆ Stavanger      ┆ [{"NSR:Quay:46 ┆ 5.73349        ┆ 58.966444      │
│ 9853            ┆            ┆ bussterminal   ┆ 967",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:2 ┆ Bus        ┆ Schweigaards   ┆ [{"NSR:Quay:45 ┆ 5.742076       ┆ 58.868973      │
│ 6142            ┆            ┆ gate           ┆ 293",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:6 ┆ Bus        ┆ Dyre Halses    ┆ [{"NSR:Quay:10 ┆ 10.414191      ┆ 63.436977      │
│ 0253            ┆            ┆ gate           ┆ 2713",2026-01- ┆                ┆                │
│                 ┆            ┆                ┆ 15…            ┆                ┆                │
│ NSR:StopPlace:4 ┆ Bus        ┆ Valøyvegen     ┆ [{"NSR:Quay:71 ┆ 10.398659      ┆ 63.408645      │
│ 2052            ┆            ┆                ┆ 981",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
│ NSR:StopPlace:2 ┆ Bus        ┆ Bekhuskaien    ┆ [{"NSR:Quay:48 ┆ 5.744252       ┆ 58.971113      │
│ 8259            ┆            ┆                ┆ 605",2026-01-1 ┆                ┆                │
│                 ┆            ┆                ┆ 5 …            ┆                ┆                │
└─────────────────┴────────────┴────────────────┴────────────────┴────────────────┴────────────────┘

In [70]:
frekvente_stoppesteder_7_18 = (
    frekvente_stoppesteder_7_18
    .with_columns(
        pl.when(pl.col("route_type")=="Bus").then(pl.lit(400)).otherwise(pl.lit(500)).alias("radius")
    )
    .with_columns(
        pl.when(pl.col("route_type")=="Bussveien").then(pl.lit("Bus")).otherwise("route_type").alias("route_type")
    )
)

frekvente_stoppesteder_7_20 = (
    frekvente_stoppesteder_7_20
    .with_columns(
        pl.when(pl.col("route_type")=="Bus").then(pl.lit(400)).otherwise(pl.lit(500)).alias("radius")
    )
    .with_columns(
        pl.when(pl.col("route_type")=="Bussveien").then(pl.lit("Bus")).otherwise("route_type").alias("route_type")
    )
)

frekvente_stoppesteder_7_18.select("stopPlaceRef", "route_type", "name", "location_longitude", "location_latitude", "radius").write_parquet("stasjoner_med_frekvens_10_15_7_18.parquet")
frekvente_stoppesteder_7_20.select("stopPlaceRef", "route_type", "name", "location_longitude", "location_latitude", "radius").write_parquet("stasjoner_med_frekvens_10_15_7_20.parquet")

In [76]:
frekvente_stoppesteder_7_18.filter(pl.col("radius")==500).group_by("route_type").len()

shape: (4, 2)
┌────────────┬─────┐
│ route_type ┆ len │
│ ---        ┆ --- │
│ str        ┆ u32 │
╞════════════╪═════╡
│ Bus        ┆ 40  │
│ Train      ┆ 33  │
│ Tram       ┆ 128 │
│ Subway     ┆ 101 │
└────────────┴─────┘

### Sjekk av Tromsø

In [72]:
(
    alle_avganger
    .filter(pl.col("agency_name")=="Svipper", pl.col("route_id").str.starts_with("TRO"))
    .sort("departure_time")
    .with_columns(waiting_time = pl.col("departure_time").shift(-1).over("name", "stop_id", "route_type") - pl.col("departure_time"))
    .filter(pl.col("departure_time").is_between(pl.datetime(2026, 1, 15, 7, time_zone="Europe/Oslo"), pl.datetime(2026, 1, 15, 19, 50, time_zone="Europe/Oslo")),
            pl.col("waiting_time").is_not_null())
    .group_by("name", "stop_id", "route_type")
    .agg(pl.col("waiting_time").max(), pl.len())
    .filter(pl.col("len")>10)
    .sort("waiting_time")
    .collect()
)

shape: (1_045, 5)
┌──────────────────────────┬─────────────────┬────────────┬──────────────┬─────┐
│ name                     ┆ stop_id         ┆ route_type ┆ waiting_time ┆ len │
│ ---                      ┆ ---             ┆ ---        ┆ ---          ┆ --- │
│ str                      ┆ str             ┆ str        ┆ duration[μs] ┆ u32 │
╞══════════════════════════╪═════════════════╪════════════╪══════════════╪═════╡
│ Skippergata              ┆ NSR:Quay:91057  ┆ Bus        ┆ 9m           ┆ 373 │
│ UiT                      ┆ NSR:Quay:89264  ┆ Bus        ┆ 10m          ┆ 272 │
│ UiT/Planetariet          ┆ NSR:Quay:89269  ┆ Bus        ┆ 10m          ┆ 272 │
│ UNN                      ┆ NSR:Quay:89250  ┆ Bus        ┆ 10m          ┆ 255 │
│ Giæverbukta bussterminal ┆ NSR:Quay:95713  ┆ Bus        ┆ 11m          ┆ 176 │
│ …                        ┆ …               ┆ …          ┆ …            ┆ …   │
│ Moan skole               ┆ NSR:Quay:93271  ┆ Bus        ┆ 5h 50m       ┆ 13  │
│ Bardu Skole              ┆ NSR:Quay:106584 ┆ Bus        ┆ 5h 55m       ┆ 13  │
│ Olsborg skole            ┆ NSR:Quay:96938  ┆ Bus        ┆ 6h 3m        ┆ 17  │
│ Olsborg                  ┆ NSR:Quay:96932  ┆ Bus        ┆ 6h 10m       ┆ 12  │
│ Vik skole                ┆ NSR:Quay:90090  ┆ Bus        ┆ 6h 38m       ┆ 13  │
└──────────────────────────┴─────────────────┴────────────┴──────────────┴─────┘

In [73]:
start_time = pl.datetime(2026, 1, 15, 7, time_zone="Europe/Oslo")
end_time = pl.datetime(2026, 1, 15, 20, time_zone="Europe/Oslo")

timedelta_bus = pl.duration(minutes=10)
timedelta_not_bus = pl.duration(minutes=15)
(
    alle_avganger
    .filter(pl.col("route_type")!="Ferry", pl.col("agency_name")=="Svipper", pl.col("route_id").str.starts_with("TRO"))
    .filter(pl.col("stop_sequence")!=pl.col("stop_sequence").max().over("trip_id"))
    .sort("departure_time")
    .with_columns(
        waiting_time = pl.col("departure_time").shift(-1).over("stop_id") - pl.col("departure_time")
    )
    .group_by(
        "stop_id", "parent_station", "stopPlaceRef", "route_type", "name"
    )
    .agg(
        max_waiting_time_bus = pl.col("waiting_time").filter(
                pl.col("departure_time")
                .is_between(
                    start_time,
                    end_time-timedelta_bus
                )
        ).max(),
        max_waiting_time_not_bus = pl.col("waiting_time").filter(
                pl.col("departure_time")
                .is_between(
                    start_time,
                    end_time-timedelta_not_bus
                )
        ).max(),
        first_departure = pl.col("departure_time").filter(pl.col("departure_time")>=start_time).min(),
        last_departure = pl.col("departure_time").filter(pl.col("departure_time")<=end_time).max(),
        len=pl.len()
    )
    .with_columns(
        pl.when(pl.col("route_type")=="Bus").then("max_waiting_time_bus").otherwise("max_waiting_time_not_bus").alias("max_waiting_time")
    )
    .drop(cs.contains("bus"))
    .filter(
        (
            (pl.col("route_type")=="Bus") & 
            (pl.col("max_waiting_time")<=timedelta_bus) & 
            (pl.col("first_departure")<=start_time + timedelta_bus) & 
            (pl.col("last_departure")>=end_time - timedelta_bus)
        ) |
        (
            (pl.col("route_type")!="Bus") & 
            (pl.col("max_waiting_time")<=timedelta_not_bus) & 
            (pl.col("first_departure")<=start_time + timedelta_not_bus) & 
            (pl.col("last_departure")>=end_time - timedelta_not_bus)
        )
    )
    .sort("len", descending=True)
    .head(12)
    .collect()
)

shape: (3, 9)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬─────┬───────────┐
│ stop_id    ┆ parent_sta ┆ stopPlaceR ┆ route_type ┆ … ┆ first_depa ┆ last_depa ┆ len ┆ max_waiti │
│ ---        ┆ tion       ┆ ef         ┆ ---        ┆   ┆ rture      ┆ rture     ┆ --- ┆ ng_time   │
│ str        ┆ ---        ┆ ---        ┆ str        ┆   ┆ ---        ┆ ---       ┆ u32 ┆ ---       │
│            ┆ str        ┆ str        ┆            ┆   ┆ datetime[μ ┆ datetime[ ┆     ┆ duration[ │
│            ┆            ┆            ┆            ┆   ┆ s, Europe/ ┆ μs, Europ ┆     ┆ μs]       │
│            ┆            ┆            ┆            ┆   ┆ Oslo]      ┆ e/Oslo]   ┆     ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═════╪═══════════╡
│ NSR:Quay:9 ┆ null       ┆ NSR:StopPl ┆ Bus        ┆ … ┆ 2026-01-15 ┆ 2026-01-1 ┆ 465 ┆ 9m        │
│ 1057       ┆            ┆ ace:53442  ┆            ┆   ┆ 07:01:00   ┆ 5         ┆     ┆           │
│            ┆            ┆            ┆            ┆   ┆ CET        ┆ 20:00:00  ┆     ┆           │
│            ┆            ┆            ┆            ┆   ┆            ┆ CET       ┆     ┆           │
│ NSR:Quay:8 ┆ null       ┆ NSR:StopPl ┆ Bus        ┆ … ┆ 2026-01-15 ┆ 2026-01-1 ┆ 324 ┆ 10m       │
│ 9269       ┆            ┆ ace:52491  ┆            ┆   ┆ 07:01:00   ┆ 5         ┆     ┆           │
│            ┆            ┆            ┆            ┆   ┆ CET        ┆ 19:54:00  ┆     ┆           │
│            ┆            ┆            ┆            ┆   ┆            ┆ CET       ┆     ┆           │
│ NSR:Quay:8 ┆ null       ┆ NSR:StopPl ┆ Bus        ┆ … ┆ 2026-01-15 ┆ 2026-01-1 ┆ 324 ┆ 10m       │
│ 9264       ┆            ┆ ace:52488  ┆            ┆   ┆ 07:02:00   ┆ 5         ┆     ┆           │
│            ┆            ┆            ┆            ┆   ┆ CET        ┆ 19:55:00  ┆     ┆           │
│            ┆            ┆            ┆            ┆   ┆            ┆ CET       ┆     ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴─────┴───────────┘

In [74]:
frekvente_stoppesteder_7_20.filter(pl.col("stopPlaceRef")=="NSR:StopPlace:52491")

shape: (1, 7)
┌───────────────┬────────────┬───────────────┬──────────────┬──────────────┬──────────────┬────────┐
│ stopPlaceRef  ┆ route_type ┆ name          ┆ stop_id      ┆ location_lon ┆ location_lat ┆ radius │
│ ---           ┆ ---        ┆ ---           ┆ ---          ┆ gitude       ┆ itude        ┆ ---    │
│ str           ┆ str        ┆ str           ┆ list[struct[ ┆ ---          ┆ ---          ┆ i32    │
│               ┆            ┆               ┆ 4]]          ┆ f64          ┆ f64          ┆        │
╞═══════════════╪════════════╪═══════════════╪══════════════╪══════════════╪══════════════╪════════╡
│ NSR:StopPlace ┆ Bus        ┆ UiT/Planetari ┆ [{"NSR:Quay: ┆ 18.970487    ┆ 69.679148    ┆ 400    │
│ :52491        ┆            ┆ et            ┆ 89269",2026- ┆              ┆              ┆        │
│               ┆            ┆               ┆ 01-15 …      ┆              ┆              ┆        │
└───────────────┴────────────┴───────────────┴──────────────┴──────────────┴──────────────┴────────┘

In [75]:
pl.Config.set_tbl_rows(10)
(
    alle_avganger
    .filter(pl.col("stop_id")=="NSR:Quay:89264")
    .sort("departure_time")
    .with_columns(waiting_time = pl.col("departure_time").shift(-1) - pl.col("departure_time"))
    .filter(pl.col("departure_time").is_between(pl.datetime(2026, 1, 15, 7, time_zone="Europe/Oslo"), pl.datetime(2026, 1, 15, 20, time_zone="Europe/Oslo")))
    .collect()
)

shape: (273, 17)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬──────┬───────────┬───────────┐
│ agency_nam ┆ route_id   ┆ route_shor ┆ route_long ┆ … ┆ stopPlace ┆ name ┆ parent_st ┆ waiting_t │
│ e          ┆ ---        ┆ t_name     ┆ _name      ┆   ┆ Ref       ┆ ---  ┆ ation     ┆ ime       │
│ ---        ┆ str        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ str  ┆ ---       ┆ ---       │
│ str        ┆            ┆ str        ┆ str        ┆   ┆ str       ┆      ┆ str       ┆ duration[ │
│            ┆            ┆            ┆            ┆   ┆           ┆      ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪══════╪═══════════╪═══════════╡
│ Svipper    ┆ TRO:Line:1 ┆ 33         ┆ Ringrute   ┆ … ┆ NSR:StopP ┆ UiT  ┆ null      ┆ 7m        │
│            ┆ _33        ┆            ┆ UNN -      ┆   ┆ lace:5248 ┆      ┆           ┆           │
│            ┆            ┆            ┆ Fagereng - ┆   ┆ 8         ┆      ┆           ┆           │
│            ┆            ┆            ┆ UNN        ┆   ┆           ┆      ┆           ┆           │
│ Svipper    ┆ TRO:Line:1 ┆ 34         ┆ UNN-Sydspi ┆ … ┆ NSR:StopP ┆ UiT  ┆ null      ┆ 0µs       │
│            ┆ _34        ┆            ┆ ssen-Sentr ┆   ┆ lace:5248 ┆      ┆           ┆           │
│            ┆            ┆            ┆ um-UNN     ┆   ┆ 8         ┆      ┆           ┆           │
│ Svipper    ┆ TRO:Line:1 ┆ 30         ┆ UNN -      ┆ … ┆ NSR:StopP ┆ UiT  ┆ null      ┆ 3m        │
│            ┆ _30        ┆            ┆ Sorgenfri  ┆   ┆ lace:5248 ┆      ┆           ┆           │
│            ┆            ┆            ┆ - UNN      ┆   ┆ 8         ┆      ┆           ┆           │
│ Svipper    ┆ TRO:Line:1 ┆ 20         ┆ Skattøra - ┆ … ┆ NSR:StopP ┆ UiT  ┆ null      ┆ 2m        │
│            ┆ _20        ┆            ┆ sentrum -  ┆   ┆ lace:5248 ┆      ┆           ┆           │
│            ┆            ┆            ┆ Kroken     ┆   ┆ 8         ┆      ┆           ┆           │
│ Svipper    ┆ TRO:Line:1 ┆ X36        ┆ Unn - Uit  ┆ … ┆ NSR:StopP ┆ UiT  ┆ null      ┆ 0µs       │
│            ┆ _36        ┆            ┆ - Åsgård - ┆   ┆ lace:5248 ┆      ┆           ┆           │
│            ┆            ┆            ┆ Myreng     ┆   ┆ 8         ┆      ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …    ┆ …         ┆ …         │
│ Svipper    ┆ TRO:Line:1 ┆ 33         ┆ Ringrute   ┆ … ┆ NSR:StopP ┆ UiT  ┆ null      ┆ 10m       │
│            ┆ _33        ┆            ┆ UNN -      ┆   ┆ lace:5248 ┆      ┆           ┆           │
│            ┆            ┆            ┆ Fagereng - ┆   ┆ 8         ┆      ┆           ┆           │
│            ┆            ┆            ┆ UNN        ┆   ┆           ┆      ┆           ┆           │
│ Svipper    ┆ TRO:Line:1 ┆ 33         ┆ Ringrute   ┆ … ┆ NSR:StopP ┆ UiT  ┆ null      ┆ 5m        │
│            ┆ _33        ┆            ┆ UNN -      ┆   ┆ lace:5248 ┆      ┆           ┆           │
│            ┆            ┆            ┆ Fagereng - ┆   ┆ 8         ┆      ┆           ┆           │
│            ┆            ┆            ┆ UNN        ┆   ┆           ┆      ┆           ┆           │
│ Svipper    ┆ TRO:Line:1 ┆ 34         ┆ UNN-Sydspi ┆ … ┆ NSR:StopP ┆ UiT  ┆ null      ┆ 0µs       │
│            ┆ _34        ┆            ┆ ssen-Sentr ┆   ┆ lace:5248 ┆      ┆           ┆           │
│            ┆            ┆            ┆ um-UNN     ┆   ┆ 8         ┆      ┆           ┆           │
│ Svipper    ┆ TRO:Line:1 ┆ 20         ┆ Skattøra - ┆ … ┆ NSR:StopP ┆ UiT  ┆ null      ┆ 5m        │
│            ┆ _20        ┆            ┆ sentrum -  ┆   ┆ lace:5248 ┆      ┆           ┆           │
│            ┆            ┆            ┆ Kroken     ┆   ┆ 8         ┆      ┆           ┆           │
│ Svipper    ┆ TRO:Line:1 ┆ 33         ┆ Ringrute   ┆ … ┆ NSR:StopP ┆ UiT  ┆ null      ┆ 10m       │
│            ┆ _33        ┆            ┆ UNN -      ┆   ┆ lace:5248 ┆      ┆           ┆           │
│            ┆            ┆            ┆ Fagereng - ┆   ┆ 8         ┆      ┆           ┆           │
│            ┆            ┆            ┆ UNN        ┆   ┆           ┆      ┆           ┆           │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴──────┴───────────┴───────────┘