# Kartutsnitt

In [1]:
import streamlit as st
import pandas as pd
import pydeck as pdk
import geopandas as gpd
import polars as pl
import os
import fiona
from dotenv import load_dotenv

In [2]:
crs_plot = "EPSG:4326"
crs_norge = "EPSG:25833"
load_dotenv()

True

In [3]:
gdf = gpd.read_file("buffrede_sentrumssoner.gpkg", engine="pyogrio")
gdf["name"] = gdf["område"].astype(str) + " - " + gdf["kommunenavn"].astype(str)
gdf = gdf.to_crs(crs_plot)
MAPBOX_TOKEN = os.getenv("MAPBOX_API_KEY")

In [4]:
områder_path = "geografiske_områder/"
område_gdf_list = []

for root, dirs, files in os.walk(områder_path):
    for f in files:
        if f.endswith("geojson"):
            l = fiona.listlayers(f"{root}/{f}")
            ll = [f for f in l if f.lower().endswith("kommune")]
            if len(ll)==1:
                ll = ll[0]
                område_gdf_list.append(gpd.read_file(f"{root}/{f}", layer=ll).assign(område = root.removeprefix("geografiske_områder/"),
                                                                                     kommune = f))
            else:
                print(f"problem med {root}/{f} og layers {l}. finn på noe smartere!")
områder_gdf = pd.concat([gdf.to_crs(crs_norge) for gdf in område_gdf_list], ignore_index=True)

områder_gdf = områder_gdf[["område", "navn", "geometry", "kommune"]]
navneliste=pl.from_pandas(områder_gdf.drop(columns=["geometry"])).select(pl.col("navn").list.get(0).struct.field("navn")).get_column("navn").to_list()
områder_gdf["kommunenavn"] = navneliste

områder_gdf

,område,navn,geometry,kommune,kommunenavn
0,Bergensområdet,"[{'navn': 'Bergen', 'rekkefolge': '', 'sprak':...","POLYGON ((-40889.251 6732715.54, -41185.821 67...",Basisdata_1201_Bergen_25832_Kommuner2019_GeoJS...,Bergen
1,Bergensområdet,"[{'navn': 'Os', 'rekkefolge': '', 'sprak': 'no...","POLYGON ((-39434.611 6710972.25, -36231.251 67...",Basisdata_1243_Os_25832_Kommuner2019_GeoJSON.g...,Os
2,Bergensområdet,"[{'navn': 'Fjell', 'rekkefolge': '', 'sprak': ...","POLYGON ((-81178.221 6744231.53, -80969.191 67...",Basisdata_1246_Fjell_25832_Kommuner2019_GeoJSO...,Fjell
3,Bergensområdet,"[{'navn': 'Askøy', 'rekkefolge': '', 'sprak': ...","POLYGON ((-48466.041 6746207.53, -46259.711 67...",Basisdata_1247_Askoy_25832_Kommuner2019_GeoJSO...,Askøy
4,Bergensområdet,"[{'navn': 'Lindås', 'rekkefolge': '', 'sprak':...","POLYGON ((-38603.821 6764433.21, -35414.481 67...",Basisdata_1263_Lindas_25832_Kommuner2019_GeoJS...,Lindås
5,Buskerudbyen,NaN,"MULTIPOLYGON (((238078.346 6609766.134, 238093...",Basisdata_3301_Drammen_25832_Kommune_GeoJSON.g...,NaN
6,Buskerudbyen,NaN,"MULTIPOLYGON (((199851.748 6629947.834, 199852...",Basisdata_3303_Kongsberg_25832_Kommune_GeoJSON...,NaN
7,Buskerudbyen,NaN,"MULTIPOLYGON (((233581.941 6631686.23, 234154....",Basisdata_3312_Lier_25832_Kommune_GeoJSON.geojson,NaN
8,Buskerudbyen,NaN,"MULTIPOLYGON (((203676.642 6639124.935, 203677...",Basisdata_3314_Ovre_Eiker_25832_Kommune_GeoJSO...,NaN
9,Grenland,NaN,"MULTIPOLYGON (((194619.667 6569622.081, 194616...",Basisdata_4001_Porsgrunn_25832_Kommune_GeoJSON...,NaN
10,Grenland,NaN,"MULTIPOLYGON (((171312.642 6571292.401, 171195...",Basisdata_4003_Skien_25832_Kommune_GeoJSON.geo...,NaN
11,Grenland,NaN,"MULTIPOLYGON (((204494.048 6583007.831, 204528...",Basisdata_4010_Siljan_25832_Kommune_GeoJSON.ge...,NaN
12,Kristiansandsområdet,NaN,"MULTIPOLYGON (((97825.65 6465753.61, 97861.11 ...",Basisdata_4204_Kristiansand_25833_Kommune_GeoJ...,NaN
13,Kristiansandsområdet,NaN,"MULTIPOLYGON (((119452.54 6445380, 120224.39 6...",Basisdata_4215_Lillesand_25833_Kommune_GeoJSON...,NaN
14,Kristiansandsområdet,NaN,"MULTIPOLYGON (((107319.44 6484522.88, 107362.5...",Basisdata_4216_Birkenes_25833_Kommune_GeoJSON....,NaN
15,Kristiansandsområdet,NaN,"MULTIPOLYGON (((95965.49 6499834.78, 96035.38 ...",Basisdata_4218_Iveland_25833_Kommune_GeoJSON.g...,NaN
16,Kristiansandsområdet,NaN,"MULTIPOLYGON (((83295.52 6478512.98, 83401.36 ...",Basisdata_4223_Vennesla_25833_Kommune_GeoJSON....,NaN
17,Nedre Glomma,NaN,"MULTIPOLYGON (((288023.971 6584473.331, 288026...",Basisdata_3105_Sarpsborg_25832_Kommune_GeoJSON...,NaN
18,Nedre Glomma,NaN,"MULTIPOLYGON (((266521.536 6580988.04, 266503 ...",Basisdata_3107_Fredrikstad_25832_Kommune_GeoJS...,NaN
19,Nord-Jæren,"[{'navn': 'Sandnes', 'rekkefolge': '', 'sprak'...","POLYGON ((-40827.921 6558704.49, -40819.811 65...",Basisdata_1102_Sandnes_25832_Kommuner2019_GeoJ...,Sandnes
20,Nord-Jæren,"[{'navn': 'Stavanger', 'rekkefolge': '', 'spra...","POLYGON ((-35706.521 6574878.88, -35703.411 65...",Basisdata_1103_Stavanger_25832_Kommuner2019_Ge...,Stavanger
21,Nord-Jæren,"[{'navn': 'Sola', 'rekkefolge': '', 'sprak': '...","POLYGON ((-74052.521 6574108.28, -73251.511 65...",Basisdata_1124_Sola_25832_Kommuner2019_GeoJSON...,Sola
22,Nord-Jæren,"[{'navn': 'Randaberg', 'rekkefolge': '', 'spra...","POLYGON ((-43609.911 6585068.08, -48033.291 65...",Basisdata_1127_Randaberg_25832_Kommuner2019_Ge...,Randaberg
23,Osloområdet,"[{'navn': 'Vestby', 'rekkefolge': '', 'sprak':...","POLYGON ((253411.31 6612055.15, 253382.12 6611...",Basisdata_0211_Vestby_25832_Kommuner2019_GeoJS...,Vestby
24,Osloområdet,"[{'navn': 'Ski', 'rekkefolge': '', 'sprak': 'n...","POLYGON ((264148.07 6629593.76, 264144.96 6629...",Basisdata_0213_Ski_25832_Kommuner2019_GeoJSON....,Ski
25,Osloområdet,"[{'navn': 'Ås', 'rekkefolge': '', 'sprak': 'no...","POLYGON ((256555.68 6622033.2, 256519.7 662196...",Basisdata_0214_As_25832_Kommuner2019_GeoJSON.g...,Ås
26,Osloområdet,"[{'navn': 'Frogn', 'rekkefolge': '', 'sprak': ...","POLYGON ((256572.1 6622068.63, 256416.58 66220...",Basisdata_0215_Frogn_25832_Kommuner2019_GeoJSO...,Frogn
27,Osloområdet,"[{'navn': 'Frogn', 'rekkefolge': '', 'sprak': ...","POLYGON ((256572.1 6622068.63, 256625.75 66220...",Basisdata_0215_Frogn_25832_Kommuner2019_GeoJSO...,Frogn
28,Osloområdet,"[{'navn': 'Nesodden', 'rekkefolge': '', 'sprak...","POLYGON ((257089.14 6646505.69, 253352.51 6641...",Basisdata_0216_Nesodden_25832_Kommuner2019_Geo...,Nesodden
29,Osloområdet,"[{'navn': 'Oppegård', 'rekkefolge': '', 'sprak...","POLYGON ((259821.81 6636210.37, 259955.71 6634...",Basisdata_0217_Oppegard_25832_Kommuner2019_Geo...,Oppegård
30,Osloområdet,"[{'navn': 'Bærum', 'rekkefolge': '', 'sprak': ...","POLYGON ((241324.47 6652868.94, 241341.91 6652...",Basisdata_0219_Berum_25832_Kommuner2019_GeoJSO...,Bærum
31,Osloområdet,"[{'navn': 'Asker', 'rekkefolge': '', 'sprak': ...","POLYGON ((239540.84 6641377, 239540.42 6641367...",Basisdata_0220_Asker_25832_Kommuner2019_GeoJSO...,Asker
32,Osloområdet,"[{'navn': 'Aurskog-Høland', 'rekkefolge': '', ...","POLYGON ((292432.76 6638675.06, 292432.35 6638...",Basisdata_0221_Aurskog-Holand_25832_Kommuner20...,Aurskog-Høland
33,Osloområdet,"[{'navn': 'Sørum', 'rekkefolge': '', 'sprak': ...","POLYGON ((283849.58 6657157.25, 283868.02 6657...",Basisdata_0226_Sorum_25832_Kommuner2019_GeoJSO...,Sørum
34,Osloområdet,"[{'navn': 'Fet', 'rekkefolge': '', 'sprak': 'n...","POLYGON ((283429.65 6647399.83, 283443.07 6647...",Basisdata_0227_Fet_25832_Kommuner2019_GeoJSON....,Fet
35,Osloområdet,"[{'navn': 'Rælingen', 'rekkefolge': '', 'sprak...","POLYGON ((277296.04 6645375.66, 277280.21 6645...",Basisdata_0228_Relingen_25832_Kommuner2019_Geo...,Rælingen
36,Osloområdet,"[{'navn': 'Enebakk', 'rekkefolge': '', 'sprak'...","POLYGON ((273964.44 6632317.13, 273942.16 6632...",Basisdata_0229_Enebakk_25832_Kommuner2019_GeoJ...,Enebakk
37,Osloområdet,"[{'navn': 'Lørenskog', 'rekkefolge': '', 'spra...","POLYGON ((271335.6 6646982.96, 271140.7 664604...",Basisdata_0230_Lorenskog_25832_Kommuner2019_Ge...,Lørenskog
38,Osloområdet,"[{'navn': 'Skedsmo', 'rekkefolge': '', 'sprak'...","POLYGON ((276445.61 6656983.43, 276440.14 6656...",Basisdata_0231_Skedsmo_25832_Kommuner2019_GeoJ...,Skedsmo
39,Osloområdet,"[{'navn': 'Nittedal', 'rekkefolge': '', 'sprak...","POLYGON ((264560.83 6669582.38, 264578.41 6669...",Basisdata_0233_Nittedal_25832_Kommuner2019_Geo...,Nittedal
40,Osloområdet,"[{'navn': 'Gjerdrum', 'rekkefolge': '', 'sprak...","POLYGON ((273757.93 6667604.77, 273776.53 6667...",Basisdata_0234_Gjerdrum_25832_Kommuner2019_Geo...,Gjerdrum
41,Osloområdet,"[{'navn': 'Ullensaker', 'rekkefolge': '', 'spr...","POLYGON ((282270.81 6674236.05, 282268.88 6674...",Basisdata_0235_Ullensaker_25832_Kommuner2019_G...,Ullensaker
42,Osloområdet,"[{'navn': 'Nes', 'rekkefolge': '', 'sprak': 'n...","POLYGON ((295979.66 6673292.65, 295980.05 6673...",Basisdata_0236_Nes_25832_Kommuner2019_GeoJSON....,Nes
43,Osloområdet,"[{'navn': 'Eidsvoll', 'rekkefolge': '', 'sprak...","POLYGON ((286819.57 6700812.85, 286782.82 6700...",Basisdata_0237_Eidsvoll_25832_Kommuner2019_Geo...,Eidsvoll
44,Osloområdet,"[{'navn': 'Nannestad', 'rekkefolge': '', 'spra...","POLYGON ((267275.95 6685336.5, 267011.96 66849...",Basisdata_0238_Nannestad_25832_Kommuner2019_Ge...,Nannestad
45,Osloområdet,"[{'navn': 'Hurdal', 'rekkefolge': '', 'sprak':...","POLYGON ((270710.4 6705658.04, 273748.26 67030...",Basisdata_0239_Hurdal_25832_Kommuner2019_GeoJS...,Hurdal
46,Osloområdet,"[{'navn': 'Oslo', 'rekkefolge': '', 'sprak': '...","POLYGON ((253222.08 6658210.13, 253240.67 6658...",Basisdata_0301_Oslo_25832_Kommuner2019_GeoJSON...,Oslo
47,Tromsø,NaN,"MULTIPOLYGON (((636372.5 7715408.11, 636601.13...",Basisdata_5501_Tromso_25833_Kommuner_GeoJSON.g...,NaN
48,Trondheimsområdet,"[{'navn': 'Trondheim', 'rekkefolge': '1', 'spr...","POLYGON ((250339.83 7036887.09, 253270.96 7034...",Basisdata_5001_Trondheim_25832_Kommuner_GeoJSO...,Trondheim
49,Trondheimsområdet,"[{'navn': 'Melhus', 'rekkefolge': '', 'sprak':...","POLYGON ((243907.28 7014490.6, 243797.19 70144...",Basisdata_5028_Melhus_25832_Kommuner_GeoJSON.g...,Melhus
50,Trondheimsområdet,"[{'navn': 'Skaun', 'rekkefolge': '', 'sprak': ...","POLYGON ((245142.53 7028084.65, 245143.34 7028...",Basisdata_5029_Skaun_25832_Kommuner_GeoJSON.ge...,Skaun
51,Trondheimsområdet,"[{'navn': 'Malvik', 'rekkefolge': '', 'sprak':...","POLYGON ((279819.11 7038729.21, 279863.7 70386...",Basisdata_5031_Malvik_25832_Kommuner_GeoJSON.g...,Malvik
52,Trondheimsområdet,"[{'navn': 'Malvik', 'rekkefolge': '', 'sprak':...","POLYGON ((293152.48 7031081.97, 293159.1 70310...",Basisdata_5031_Malvik_25832_Kommuner_GeoJSON.g...,Malvik
53,Trondheimsområdet,"[{'navn': 'Malvik', 'rekkefolge': '', 'sprak':...","POLYGON ((292665.55 7030939.87, 292666.43 7030...",Basisdata_5031_Malvik_25832_Kommuner_GeoJSON.g...,Malvik
54,Trondheimsområdet,"[{'navn': 'Stjørdal', 'rekkefolge': '', 'sprak...","POLYGON ((283687.35 7047592.53, 286564.21 7044...",Basisdata_5035_Stjordal_25832_Kommuner_GeoJSON...,Stjørdal
55,Trondheimsområdet,"[{'navn': 'Orkland', 'rekkefolge': '', 'sprak'...","POLYGON ((219188.11 7028686.36, 218751.11 7028...",Basisdata_5059_Orkland_25832_Kommuner_GeoJSON....,Orkland

In [5]:
# 2. Last Parquet-filer
df_7_18 = pd.read_parquet("stasjoner_med_frekvens_10_15_7_18.parquet")

gdf_7_18 = gpd.GeoDataFrame(
    df_7_18,
    geometry=gpd.points_from_xy(
        df_7_18["location_longitude"], df_7_18["location_latitude"]
    ),
    crs=crs_plot,
)
gdf_7_18["geometry"] = (
    gdf_7_18.to_crs(crs_norge).buffer(gdf_7_18["radius"]).to_crs(crs_plot)
)

df_7_20 = pd.read_parquet("stasjoner_med_frekvens_10_15_7_20.parquet")

gdf_7_20 = gpd.GeoDataFrame(
    df_7_20,
    geometry=gpd.points_from_xy(
        df_7_20["location_longitude"], df_7_20["location_latitude"]
    ),
    crs=crs_plot,
)

gdf_7_20["geometry"] = (
    gdf_7_20.to_crs(crs_norge).buffer(gdf_7_20["radius"]).to_crs(crs_plot)
)

In [6]:
gdf_7_18

,stopPlaceRef,route_type,name,location_longitude,location_latitude,radius,geometry
0,NSR:StopPlace:3776,Bus,Stabekk kino,10.601667,59.909478,400,"POLYGON ((10.6088 59.90972, 10.60881 59.90936,..."
1,NSR:StopPlace:5630,Bus,Nordre Gran,10.902732,59.941875,400,"POLYGON ((10.90987 59.9421, 10.90988 59.94174,..."
2,NSR:StopPlace:202,Train,Holmlia stasjon,10.797166,59.835163,500,"POLYGON ((10.80606 59.83545, 10.80607 59.83501..."
3,NSR:StopPlace:26244,Bussveien,Skadbergbakken,5.660958,58.884317,500,"POLYGON ((5.66952 58.88494, 5.66959 58.8845, 5..."
4,NSR:StopPlace:60447,Bus,Buran,10.425047,63.436397,400,"POLYGON ((10.43304 63.43665, 10.43306 63.4363,..."
...,...,...,...,...,...,...,...
1198,NSR:StopPlace:30159,Tram,Kokstadflaten,5.244435,60.291936,500,"POLYGON ((5.25335 60.2926, 5.25344 60.29216, 5..."
1199,NSR:StopPlace:31223,Bus,Li,5.346161,60.463814,400,"POLYGON ((5.35333 60.46434, 5.3534 60.46399, 5..."
1200,NSR:StopPlace:30867,Tram,Nygård,5.332619,60.384529,500,"POLYGON ((5.34156 60.38518, 5.34165 60.38475, ..."
1201,NSR:StopPlace:4327,Bus,Frogner kirke,10.707320,59.917678,400,"POLYGON ((10.71445 59.91791, 10.71446 59.91756..."
1202,NSR:StopPlace:62104,Tram,Fyllingsdalen terminal,5.289062,60.348667,500,"POLYGON ((5.29799 60.34932, 5.29808 60.34889, ..."

In [7]:
for loop_område, loop_gdf in områder_gdf.to_crs(crs_plot).groupby("område"):
    layers = []
    loop_sentrumsområder = gdf.sjoin(loop_gdf[["område", "geometry"]], how="inner")
    layers.append(
            pdk.Layer(
                "GeoJsonLayer",
                loop_sentrumsområder,
                opacity=0.5,
                get_fill_color=[20, 100, 200, 150],
                get_line_color=[255, 255, 255],
                pickable=True,
            )
        )

    loop_gdf_7_20 = gdf_7_20.sjoin(loop_gdf[["område", "geometry"]], how="inner")
    if loop_gdf_7_20.shape[0]>0:
        layers.append(
            pdk.Layer(
                "GeoJsonLayer",
                loop_gdf_7_20.query("(route_type=='Bus') | (route_type=='Bussveien')"),
                stroked=True,
                get_line_width=25,
                get_line_color=[255, 150, 0, 240],
                get_fill_color=[68, 79, 85, 0],
                pickable=True,
            )
        )
        layers.append(
                pdk.Layer(
                    "GeoJsonLayer",
                    loop_gdf_7_20.query("(route_type!='Bus') & (route_type!='Bussveien')"),
                    stroked=True,
                    get_line_width=25,
                    get_line_color=[68, 79, 85, 240],
                    get_fill_color=[68, 79, 85, 0],
                    pickable=True,
                )
            )
    

        initial_view = pdk.data_utils.compute_view(loop_gdf_7_20[["location_longitude", "location_latitude"]].values, view_proportion=1)
    else:
        initial_view = pdk.ViewState(longitude=10, latitude=60, zoom=6)
    r = pdk.Deck(
        layers=layers, 
        initial_view_state=initial_view, 
        api_keys={"mapbox":MAPBOX_TOKEN}, 
        views=[{"@@type": "MapView", "controller": True}],
        map_style="light",
        map_provider="mapbox"
    )
    r.to_html(f"screenshot_{loop_område}.html")